name: barber_shop_admin
description: A new Flutter application.




version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  cloud_firestore: ^0.14.4
  firebase_core: ^0.5.3
  firebase_storage: ^5.2.0
  firebase_auth: ^0.18.4+1
  random_string: ^2.1.0
  persistent_bottom_nav_bar: ^3.1.0
  intl: ^0.16.1
  provider: ^4.3.2+3
  image_picker: ^0.6.7+21
  modal_progress_hud: ^0.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

